# Generated by Django 3.0.2 on 2020-01-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chara',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chara',
            name='species',
            field=models.CharField(default='human', max_length=200, null=True),
        ),
    ]
