# Generated by Django 3.0.2 on 2020-01-27 02:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bios', '0002_auto_20200126_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chara',
            new_name='Character',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='bio',
            new_name='bio_text',
        ),
    ]
